---
language: python
python: "2.7"

services:
  - rabbitmq


before_install:
  # Make sure everything's up to date.
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository -y cloud-archive:icehouse
  - sudo apt-get update -qq


install:
  # Install Ansible.
  - sudo pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"


script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local
    --sudo

  # Test role idempotency
  - >
    ansible-playbook -i tests/inventory tests/test.yml -t neutron-dhcp-agent
    --connection=local --sudo | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Test serice status
  - service neutron-dhcp-agent status


#  - sudo cat /var/log/keystone/keystone-all.log
#  - sudo cat /var/log/glance/api.log
#  - sudo cat /var/log/nova/nova-api.log
#  - sudo cat /var/log/neutron/server.log
