---

- name: Configure dnsmasq
  lineinfile: dest=/etc/neutron/dnsmasq-neutron.conf
              regexp=^dhcp-option-force=
              line=dhcp-option-force=26,1454
              create=True
  notify:
    - Kill all dnsmasq
